server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ffraga98/especializacion-backend-i-parcial
          default-label: main
          force-pull: true
          source-paths: configuration
